Awesome books with ES6
dfsalam/awesome-books-es6 pull request #1
Opened 2023-01-17 18:33 UTC by dfsalam

- Create index.html, index.js, index.css files
- Divide the code into modules.
- Install the luxon library.
- Create the date function with DateTime.
- Fix linter errors.
- Fix readme file.

2023-01-17 19:36 UTC, danmainah requested changes
Hi @dfsalam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-17 19:36 UTC, danmainah commented on modules/Books.js
> +  }
- [ ] [optional] @dfsalam great work on your modules, however, It would be even better if you had extra modules to create and delete books.

2023-01-17 19:36 UTC, danmainah commented on modules/Book.js
> +  }
- [ ] @dfsalam great work on your functions, however as part of the requirement kindly change your function to an arrow function only the constructor method is exempted, its part of ES6 syntax.
![image](https://user-images.githubusercontent.com/61408860/212994577-8c8aa8dd-cb45-45b6-888d-0bcc74511418.png)

2023-01-17 19:36 UTC, danmainah commented on modules/Books.js
> +  }
- [ ] @dfsalam great work on your functions, however as part of the requirement kindly change your function to an arrow function only the constructor method is exempted, it's part of ES6 syntax.
![image](https://user-images.githubusercontent.com/61408860/212994577-8c8aa8dd-cb45-45b6-888d-0bcc74511418.png)

2023-01-18 01:21 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @dfsalam ,

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Modules used ✔️
- ES6 and arrow functions Used ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 01:27 UTC, merged